version: "3"
services:
  front_app_test_message:
    restart: always
    build: .
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - CI=true